### ISSUE TITLE
Mail for good

### ISSUE THREAD

**Issue by vadim9999** [ChickenKyiv/amazon-ses-service#47]

**Comment by vadim9999** [comment]
https://github.com/matomo-org/matomo/issues/15308

**Comment by vadim9999** [comment]
[geoip lite](https://github.com/matomo-org/matomo/issues/15308)

**Comment by vadim9999** [comment]
Development working using node version 8.17.0. node version 8.2.1. not working problem with some package in node_moules
Docker -project running but when click login get redirect with internal server error

**Comment by atherdon** [comment]
show me how it looks :)

>

**Comment by vadim9999** [comment]
![image](https://user-images.githubusercontent.com/35640573/80313152-da721880-87f1-11ea-8f7b-4cf40590f509.png)

**Comment by atherdon** [comment]
tell me more!

>

**Comment by atherdon** [comment]
looks awesome

**Comment by vadim9999** [comment]
I spent 2 hours and it's still not working. 

to run this project first of all need to delete `^` in package.json (lock all project dependencies). then install sass

but I get error when going on localhost:8080
```
TypeError: req.session.touch is not a function
    at ServerResponse.end (/home/vadim/js/groceristar/mail-for-good/node_modules/express-session/index.js:325:21)
    at ServerResponse.send (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/response.js:211:10)
    at apiIsAuth (/home/vadim/js/groceristar/mail-for-good/server/routes/middleware/auth.js:16:23)
    at Layer.handle [as handle_request] (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/layer.js:95:5)
    at /home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:275:10)
    at _cookieSession (/home/vadim/js/groceristar/mail-for-good/node_modules/cookie-session/index.js:126:5)
    at Layer.handle [as handle_request] (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:317:13)
    at /home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/vadim/js/groceristar/mail-for-good/node_modules/express/lib/router/index.js:275:10)

```

**Comment by vadim9999** [comment]
I think this problem in this line code https://github.com/freeCodeCamp/mail-for-good/blob/master/server/config/server/session.js#L8
but I can't figure out why (all installed ok)
npm run build complete without any error.
npm start also
but problem when session that creates server using redis-server and session

**Comment by atherdon** [comment]
we can try something together. as it should be setup gently - we must use
your machine for it
can you push code at someplace? i want to try to run that code at some
online sandbox - maybe I'll have luck and get the same errors you have

>

**Comment by vadim9999** [comment]
I didn't do anything with code. I just added creds into my .env file. I don't think you will run this project on the online sandbox. You need a docker to run it or installed redis-server and postgresql.

**Comment by vadim9999** [comment]
Sorry Arthur, I don't know what to do now. I don't know anything about redis-server and js library that working with a session on the server (`express-session` and `connect-redis`). Trying to fix the problem without understanding what is going on isn't a good idea. 
I see two variants for solving this problem:
1. maybe I something doing wrong or redis-server not configured properly. If we need this project I can learn deeper how these libraries works. Starting from zero. create an empty project and create a server that will be creating sessions. But it can take more time. The estimation of time starts from 16- 24 hours
2. Remove all functionality related to authentication, authorization, writing into PostgreSQL. And grub code that working with was ses.
Any ideas?

**Comment by vadim9999** [comment]
@atherdon
